/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as PrintRouteImport } from './routes/print'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/exam': typeof ExamRoute
  '/print': typeof PrintRoute
  '/quiz': typeof QuizRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/exam': typeof ExamRoute
  '/print': typeof PrintRoute
  '/quiz': typeof QuizRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/exam': typeof ExamRoute
  '/print': typeof PrintRoute
  '/quiz': typeof QuizRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cheatsheet' | '/exam' | '/print' | '/quiz' | '/topics/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cheatsheet' | '/exam' | '/print' | '/quiz' | '/topics/$slug'
  id:
    | '__root__'
    | '/'
    | '/cheatsheet'
    | '/exam'
    | '/print'
    | '/quiz'
    | '/topics/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheatsheetRoute: typeof CheatsheetRoute
  ExamRoute: typeof ExamRoute
  PrintRoute: typeof PrintRoute
  QuizRoute: typeof QuizRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheatsheetRoute: CheatsheetRoute,
  ExamRoute: ExamRoute,
  PrintRoute: PrintRoute,
  QuizRoute: QuizRoute,
  TopicsSlugRoute: TopicsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
